alias: Turn everything off when the house is empty
trigger:
  platform: state
  entity_id: group.family
  from: 'home'
condition:
  condition: state
  entity_id: input_boolean.guest_mode
  state: 'off'
action:
  - service: light.turn_off
    data:
      entity_id: 
        group.all_lights

  - service: media_player.turn_off
    data:
      entity_id:
        media_player.samsung_led55_un55f7100