alias: Laundry Room Motion turns on lights
trigger:
  platform: state
  entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar_2
  from: '0'
  to: '8'
action:
  service: light.turn_on 
  data:
    brightness: 255
    entity_id:
    - light.laundry_room
    - light.laundry_room_storage
    - light.hue_white_lamp_1_3