alias: Turn off laundry room lights 5 minutes after last movement
trigger:
  platform: state
  entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar_2
  to: '0'
  for:
    minutes: 5
action:
  service: light.turn_off 
  entity_id:
    - light.laundry_room
    - light.laundry_room_storage
    - light.hue_white_lamp_1_3