alias: Turn the lights off when everybody leaves
trigger:
  platform: state
  entity_id: group.family
  from: 'home'
condition:
  condition: state
  entity_id: input_boolean.guest_mode
  state: 'off'
action:
  entity_id: group.all_lights
  service: light.turn_off